# Generated by Django 5.2.7 on 2026-04-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfile',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='size',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
