import re
import random
import string
import json
import time
from drf_yasg.utils import swagger_auto_schema
from drf_yasg import openapi
from rest_framework.views import APIView
from rest_framework.response import Response
import openai

openai.api_key = "YOUR_OPENAI_API_KEY"

dynamic_apis = {}

def generate_random_slug(length=10):
    return ''.join(random.choices(string.ascii_letters + string.digits, k=length))

def generate_data_with_ai(prompt, retries=3, delay=1):
    """
    Generate JSON data based on user prompt using OpenAI
    retries: number of times to retry if RateLimitError occurs
    delay: seconds to wait between retries
    """
    for attempt in range(retries):
        try:
            response = openai.ChatCompletion.create(
                model="gpt-4o-mini",
                messages=[
                    {"role": "system", "content": "You are an AI assistant that generates JSON only."},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.7
            )
            content = response.choices[0].message.content
            try:
                data = json.loads(content)
            except json.JSONDecodeError:
                data = [{"error": "AI failed to generate valid JSON"}]
            return data
        except openai.error.RateLimitError:
            if attempt < retries - 1:
                time.sleep(delay)
            else:
                return [{"error": "Rate limit exceeded, try again later"}]
        except Exception as e:
            return [{"error": str(e)}]


prompt_param = openapi.Parameter(
    'prompt', openapi.IN_BODY,
    description="User writes a prompt to create an API, e.g., 'Book API required, fields: name,file,status, count: 30'",
    type=openapi.TYPE_STRING,
    required=True
)

class DynamicAPI(APIView):
    @swagger_auto_schema(
        request_body=openapi.Schema(
            type=openapi.TYPE_OBJECT,
            properties={'prompt': openapi.Schema(type=openapi.TYPE_STRING)}
        ),
        responses={200: openapi.Schema(
            type=openapi.TYPE_OBJECT,
            properties={
                'api_link': openapi.Schema(type=openapi.TYPE_STRING, description="Dynamic API link"),
                'message': openapi.Schema(type=openapi.TYPE_STRING, description="Number of items generated by AI")
            }
        )},
        operation_description="Generate AI JSON based on user prompt and return a link"
    )
    def post(self, request):
        prompt = request.data.get("prompt", "")
        count_match = re.search(r"count:\s*(\d+)", prompt)
        count = int(count_match.group(1)) if count_match else 10
        data = generate_data_with_ai(prompt)

        if isinstance(data, list) and len(data) < count:
            for i in range(len(data), count):
                data.append({"item": f"Item {i+1}"})
        elif isinstance(data, list) and len(data) > count:
            data = data[:count]

        slug = generate_random_slug()
        dynamic_apis[slug] = {"data": data}

        api_link = f"http://127.0.0.1:8000/api/{slug}/"
        return Response({"api_link": api_link, "message": f"{len(data)} items generated by AI"})

class DynamicAPIData(APIView):
    @swagger_auto_schema(
        responses={200: openapi.Schema(
            type=openapi.TYPE_ARRAY,
            items=openapi.Items(type=openapi.TYPE_OBJECT)
        )},
        operation_description="Retrieve data from a previously generated dynamic API link"
    )
    def get(self, request, slug):
        api_data = dynamic_apis.get(slug)
        if not api_data:
            return Response({"error": "API not found"}, status=404)
        return Response(api_data["data"])
