# Generated by Django 5.2.7 on 2025-10-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='User', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
