# Generated by Django 5.2.7 on 2025-10-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/default_user_p.png', null=True, upload_to='profiles/'),
        ),
    ]
