# Generated by Django 5.2.7 on 2025-10-23 18:41

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(default='User', max_length=2),
            preserve_default=False,
        ),
    ]
