# Generated by Django 5.2.7 on 2026-03-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('UZ', 'Uzbekistan'), ('KZ', 'Kazakhstan'), ('TR', 'Turkey'), ('US', 'United States')], max_length=50, null=True),
        ),
    ]
