# Generated by Django 5.2.7 on 2026-05-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockapi',
            name='admin_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
