# Generated by Django 5.2.7 on 2025-10-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('email', 'Email'), ('system', 'System'), ('info', 'Info')], default='system', max_length=20),
        ),
    ]
