# Generated by Django 5.2.7 on 2025-10-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_alter_notification_options_alter_notification_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('email', 'Email'), ('system', 'System')], default='system', max_length=20),
        ),
    ]
